import React from "react";
import {
  Type,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  ListChecks,
  Quote,
  CodeXml,
  ImageIcon,
  TableIcon,
  Minus,
  Youtube,
  MessageSquareQuote,
  Film,
  Music,
  FileText,
  Paperclip,
  MonitorPlay,
  PanelTop,
  Lightbulb,
  MousePointerClick,
  ChevronRightSquare,
} from "lucide-react";

/** Icon for each SlashCommandItem.icon key. */
export const COMMAND_ICONS: Record<string, React.ReactNode> = {
  text: <Type size={18} />,
  "heading-1": <Heading1 size={18} />,
  "heading-2": <Heading2 size={18} />,
  "heading-3": <Heading3 size={18} />,
  list: <List size={18} />,
  "list-ordered": <ListOrdered size={18} />,
  "list-checks": <ListChecks size={18} />,
  toggle: <ChevronRightSquare size={18} />,
  banner: <PanelTop size={18} />,
  callout: <Lightbulb size={18} />,
  button: <MousePointerClick size={18} />,
  quote: <Quote size={18} />,
  "message-square-quote": <MessageSquareQuote size={18} />,
  "code-xml": <CodeXml size={18} />,
  table: <TableIcon size={18} />,
  minus: <Minus size={18} />,
  image: <ImageIcon size={18} />,
  video: <Film size={18} />,
  audio: <Music size={18} />,
  pdf: <FileText size={18} />,
  file: <Paperclip size={18} />,
  embed: <MonitorPlay size={18} />,
  youtube: <Youtube size={18} />,
};
