export const SVGs = {
	next: require("../svgs/Next.svg").default,
	previous: require("../svgs/previous.svg").default,
	cloud: require("../svgs/cloud.svg").default.src,
	play: require("../svgs/play.svg").default,
	email: require("../svgs/location.svg").default,
	location: require("../svgs/location.svg").default,
	phone: require("../svgs/phone.svg").default,
	facebook: require("../svgs/facebook.svg").default.src,
	youtube: require("../svgs/youtube.svg").default.src,
	instagram: require("../svgs/instagram.svg").default.src,
	gobackward: require("../svgs/gobackward.svg").default,
	goforward: require("../svgs/goforward.svg").default,
	playF: require("../svgs/playF.svg").default,
	pauseF: require("../svgs/pauseF.svg").default,
	w_youtube: require("../svgs/w_youtube.svg").default,
	linkedin: require("../svgs/linkedin.svg").default,
	NotFound: require("../svgs/NotFound.svg").default.src,
	visibility: require("./visibility_FILL0_wght400_GRAD0_opsz48.svg").default
		.src,
	visibility_off: require("./visibility_off_FILL0_wght400_GRAD0_opsz48.svg")
		.default.src,
	Trophy: require("../svgs/trophy-circle.svg").default,
	chevronUp: require("../svgs/chevron.up.circle.svg").default,
	TrophyCircle: require("../svgs/trophy.circle.fill.svg").default,
	climb: require("../svgs/climb.svg").default,
	Vector: require("../svgs/Vector.svg").default,
	twitter: require("../svgs/twitter.svg").default,
	medal: require("../svgs/medal.svg").default,
	plane: require("../svgs/plane.svg").default,
	squareAndArrow: require("../svgs/square.and.arrow.up.svg").default,
	uploads: require("../svgs/upload.svg").default,
	settings: require("../svgs/video-icons/settings.svg").default.src,
	highVolume: require("../svgs/video-icons/high-volume.svg").default.src,
	halfVolume: require("../svgs/video-icons/half-volume.svg").default.src,
	muteVolume: require("../svgs/video-icons/mute-volume.svg").default.src,
	fullScreen: require("../svgs/video-icons/full-screen.svg").default.src,
};
