export const SVGs = {
  next: require("./Next.svg").default,
  previous: require("./previous.svg").default,
  cloud: require("./cloud.svg").default.src,
  play: require("./play.svg").default,
  email: require("./location.svg").default,
  location: require("./location.svg").default,
  phone: require("./phone.svg").default,
  facebook: require("./facebook.svg").default.src,
  youtube: require("./youtube.svg").default.src,
  instagram: require("./instagram.svg").default.src,
  gobackward: require("./gobackward.svg").default,
  goforward: require("./goforward.svg").default,
  playF: require("./playF.svg").default,
  pauseF: require("./pauseF.svg").default,
  w_youtube: require("./w_youtube.svg").default,
  linkedin: require("./linkedin.svg").default,
  NotFound: require("./NotFound.svg").default.src,
  visibility: require("./visibility_FILL0_wght400_GRAD0_opsz48.svg").default
    .src,
  visibility_off: require("./visibility_off_FILL0_wght400_GRAD0_opsz48.svg")
    .default.src,
  Trophy: require("./trophy-circle.svg").default,
  chevronUp: require("./chevron.up.circle.svg").default,
  TrophyCircle: require("./trophy.circle.fill.svg").default,
  climb: require("./climb.svg").default,
  Vector: require("./Vector.svg").default,
  twitter: require("./twitter.svg").default,
  medal: require("./medal.svg").default,
  plane: require("./plane.svg").default,
  squareAndArrow: require("./square.and.arrow.up.svg").default,
  uploads: require("./upload.svg").default,
  settings: require("./video-icons/settings.svg").default.src,
  highVolume: require("./video-icons/high-volume.svg").default.src,
  halfVolume: require("./video-icons/half-volume.svg").default.src,
  muteVolume: require("./video-icons/mute-volume.svg").default.src,
  fullScreen: require("./video-icons/full-screen.svg").default.src,
};
